/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarCropUpload: typeof import('./src/components/AvatarCropUpload.vue')['default']
    Cropper: typeof import('./src/components/Cropper.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    EmojiPicker: typeof import('./src/components/EmojiPicker.vue')['default']
    GlobalHeader: typeof import('./src/components/GlobalHeader.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Share: typeof import('./src/components/Share.vue')['default']
    Sider: typeof import('./src/components/Sider.vue')['default']
  }
}
